In [ ]:
import anndata as ad
import pandas as pd
import scipy.sparse as sp
import numpy as np
import os


sample_id = [
    "H20.33.035", "H21.33.038", "H20.33.004", "H21.33.023", "H21.33.001", "H21.33.025", "H21.33.032",
    "H21.33.031", "H21.33.019", "H21.33.016", "H20.33.040", "H20.33.012", "H20.33.025", "H21.33.015",
    "H21.33.005", "H21.33.040", "H21.33.028", "H21.33.012", "H20.33.015", "H20.33.044", "H21.33.022",
    "H21.33.011", "H21.33.013", "H21.33.014", "H21.33.021", "H21.33.006"
]


#sample_id = ["H21.33.028"]

for i in sample_id:
    os.chdir(r"D:\Research_project\For Test\smoothie\smoothie_input\celltype_specific\csv")
    counts_df = pd.read_csv(f"sample_{i}_counts.csv", index_col=0)
    spatial_df = pd.read_csv(f"sample_{i}_spatial.csv")

    adata = ad.AnnData(X=sp.csr_matrix(counts_df.values))
    adata.var_names = counts_df.columns
    adata.obs_names = counts_df.index
    adata.obsm["spatial"] = spatial_df.values  # numpy array, shape (n_cells, 2)

    os.chdir(r"D:\Research_project\For Test\smoothie\smoothie_input\celltype_specific\h5ad")
    adata.write_h5ad(f"{i}.h5ad")


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:812: UserWarning: 
AnnData expects .obs.index to contain strings, but got values like:
    [1, 2, 3, 4, 5]

    Inferred to be: integer

  names = self._prep_dim_index(names, "obs")
f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:812: UserWarning: 
AnnData expects .obs.index to contain strings, but got values like:
    [1, 2, 3, 4, 5]

    Inferred to be: integer

  names = self._prep_dim_index(names, "obs")
f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:812: UserWarning: 
AnnData expects .obs.index to contain strings, but got values like:
    [1, 2, 3, 4, 5]

    Inferred to be: integer

  names = self._prep_dim_index(names, "obs")
f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:812: UserWarning: 
AnnData expects .obs.index to contain strings, but got values like:
    [1, 2, 3, 4, 5]

    Inferred to be: integer

  names = self._prep_dim_index(na

In [ ]:
import anndata as ad
import os

os.chdir(r"D:\Research_project\For Test\smoothie\smoothie_input\celltype_specific\Oli\h5ad")
adata = ad.read_h5ad("H20.33.004.h5ad")


print(adata)


print(adata.X.shape)

print(adata.obs_names[:5])


print(adata.var_names[:5])

print(adata.obsm["spatial"][:5])


In [ ]:
import anndata as ad
import numpy as np
import scanpy as sc
import sys
import os
import scipy
import pandas as pd

sys.path.append("D:\Research_project\For Test\smoothie\src")
from gaussian_smoothing import run_parallelized_smoothing
from spatial_correlation import compute_correlation_matrix
from network_analysis import make_spatial_network

input_path = r"D:\Research_project\For Test\smoothie\smoothie_input\celltype_specific\h5ad"

sample_id = [
    "H20.33.035", "H21.33.038", "H20.33.004", "H21.33.023", "H21.33.001", "H21.33.025", "H21.33.032",
    "H21.33.031", "H21.33.019", "H21.33.016", "H20.33.040", "H20.33.012", "H20.33.025", "H21.33.015",
    "H21.33.005", "H21.33.040", "H21.33.028", "H21.33.012", "H20.33.015", "H20.33.044", "H21.33.022",
    "H21.33.011", "H21.33.013", "H21.33.014", "H21.33.021", "H21.33.006"
]



for id in sample_id:   
        print(f"processing {id}...")
        # h5ad data are the same for different smoothie methods
        os.chdir(input_path)
        adata = ad.read_h5ad(f"{id}.h5ad")
        
        if id == "H21.33.032":
                min_spot = 5
                gaus_sd = 70

        else:
                min_spot = 20
                gaus_sd = 50
        


        sc.pp.normalize_total(adata, target_sum=1e3)
        sc.pp.log1p(adata)

        sm_adata = run_parallelized_smoothing(
            adata,
            grid_based_or_not=False,      
            gaussian_sd=gaus_sd,            
            min_spots_under_gaussian=min_spot
        )
        sm_adata = sm_adata[adata.obs_names].copy()

        smoothed_matrix = sm_adata.X.toarray() if scipy.sparse.issparse(sm_adata.X) else sm_adata.X
        df = pd.DataFrame(smoothed_matrix, index=sm_adata.obs_names, columns=sm_adata.var_names)

        os.chdir(r"D:\Research_project\For Test\smoothie\smoothie_output\celltype_specific\parameters_setting_1\csv\Astrocyte")
        df.to_csv(f"{id}_smoothed_expression_matrix.csv")


print("all patients complete")


processing H20.33.035...


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Storage for smoothed count matrix will be 0.02 GB. 

Gaussian smoothing running on chunk 1 of 4... 
Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 93.83 seconds.
H20.33.035 complete...
processing H21.33.038...
Storage for smoothed count matrix will be 0.00 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 72.79 seconds.
H21.33.038 complete...
processing H20.33.004...
Storage for smoothed count matrix will be 0.01 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 75.11 seconds.
H20.33.004 complete...
processing H21.33.023...
Storage for smoothed count matrix will be 0.01 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 73.15 seconds.
H21.33.023 complete...
processing H21.33.001...


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Storage for smoothed count matrix will be 0.02 GB. 

Gaussian smoothing running on chunk 1 of 4... 
Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 82.48 seconds.
H21.33.001 complete...
processing H21.33.025...
Storage for smoothed count matrix will be 0.01 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 76.34 seconds.
H21.33.025 complete...
processing H21.33.032...
Storage for smoothed count matrix will be 0.00 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 70.91 seconds.
H21.33.032 complete...
processing H21.33.031...


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Storage for smoothed count matrix will be 0.03 GB. 

Gaussian smoothing running on chunk 1 of 4... 
Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 97.97 seconds.
H21.33.031 complete...
processing H21.33.019...
Storage for smoothed count matrix will be 0.01 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 61.15 seconds.
H21.33.019 complete...
processing H21.33.016...
Storage for smoothed count matrix will be 0.01 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 65.84 seconds.
H21.33.016 complete...
processing H20.33.040...
Storage for smoothed count matrix will be 0.01 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 69.82 seconds.
H20.33.040 complete...
processing H20.33.012...
Storage for smoothed count matrix will be 0.01 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 73.09 seconds.
H20.33.012 complete...
processing H20.33.025...
Storage for smoothed count matrix will be 0.01 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 77.03 seconds.
H20.33.025 complete...
processing H21.33.015...
Storage for smoothed count matrix will be 0.01 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 79.83 seconds.
H21.33.015 complete...
processing H21.33.005...
Storage for smoothed count matrix will be 0.00 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 71.10 seconds.
H21.33.005 complete...
processing H21.33.040...
Storage for smoothed count matrix will be 0.01 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 75.64 seconds.
H21.33.040 complete...
processing H21.33.028...
Storage for smoothed count matrix will be 0.00 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 77.95 seconds.
H21.33.028 complete...
processing H21.33.012...
Storage for smoothed count matrix will be 0.01 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 73.06 seconds.
H21.33.012 complete...
processing H20.33.015...
Storage for smoothed count matrix will be 0.01 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 79.49 seconds.
H20.33.015 complete...
processing H20.33.044...
Storage for smoothed count matrix will be 0.01 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 77.24 seconds.
H20.33.044 complete...
processing H21.33.022...
Storage for smoothed count matrix will be 0.01 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 75.29 seconds.
H21.33.022 complete...
processing H21.33.011...
Storage for smoothed count matrix will be 0.01 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 77.99 seconds.
H21.33.011 complete...
processing H21.33.013...
Storage for smoothed count matrix will be 0.01 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 77.54 seconds.
H21.33.013 complete...
processing H21.33.014...


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Storage for smoothed count matrix will be 0.02 GB. 

Gaussian smoothing running on chunk 1 of 4... 
Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 82.33 seconds.
H21.33.014 complete...
processing H21.33.021...
Storage for smoothed count matrix will be 0.00 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 74.82 seconds.
H21.33.021 complete...
processing H21.33.006...
Storage for smoothed count matrix will be 0.01 GB. 

Gaussian smoothing running on chunk 1 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


Gaussian smoothing running on chunk 2 of 4... 
Gaussian smoothing running on chunk 3 of 4... 
Gaussian smoothing running on chunk 4 of 4... 


f:\Anaconda\envs\scanpy_env\lib\site-packages\anndata\_core\anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(


Total runtime for in-place Gaussian smoothing: 77.43 seconds.
H21.33.006 complete...
all patients complete


In [15]:
import scipy
import pandas as pd

print(sm_adata)
print(sm_adata.obs_names) 
print(sm_adata.X)
print(adata.obs_names)

smoothed_matrix = sm_adata.X.toarray() if scipy.sparse.issparse(sm_adata.X) else sm_adata.X
print(smoothed_matrix)

df = pd.DataFrame(smoothed_matrix, index=sm_adata.obs_names, columns=sm_adata.var_names)
os.chdir(r"D:\Research_project\For Test\smoothie\smoothie_output\celltype_specific\csv")
df.to_csv("smoothed_expression_matrix.csv")


AnnData object with n_obs × n_vars = 8195 × 140
    uns: 'log1p'
    obsm: 'spatial'
Index(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
       ...
       '8186', '8187', '8188', '8189', '8190', '8191', '8192', '8193', '8194',
       '8195'],
      dtype='object', length=8195)
[[0.18879184 0.13187484 0.33000073 ... 0.2988179  0.28256217 0.00879434]
 [0.35590452 0.02783684 0.32325906 ... 0.6772502  0.3278544  0.0506315 ]
 [0.29061565 0.11735065 0.41321918 ... 0.7767584  0.47090858 0.24211514]
 ...
 [0.44307652 0.09851348 0.40801826 ... 0.52785826 0.63138527 0.19294134]
 [0.21605279 0.02885295 0.54275167 ... 0.6036896  0.71004987 0.21140891]
 [0.35252944 0.09771866 0.4945109  ... 0.76246583 0.60854197 0.12432646]]
Index(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
       ...
       '8186', '8187', '8188', '8189', '8190', '8191', '8192', '8193', '8194',
       '8195'],
      dtype='object', length=8195)
[[0.18879184 0.13187484 0.33000073 ... 0.2988179  0.28256217 0.00879434]


In [ ]:
import numpy as np
import os
import pandas as pd

cell_type_name = "Oli"
smoothie_method_type = "grid_based_smoothie"

folder = os.path.join(
    r"D:\Research_project\For Test\smoothie\smoothie_output\celltype_specific",
    cell_type_name,
    smoothie_method_type ,
    "npy"
)
folder_1 = os.path.join(
    r"D:\Research_project\For Test\smoothie\smoothie_output\celltype_specific",
    cell_type_name,
    smoothie_method_type ,
    "csv"
)
file_list = sorted([f for f in os.listdir(folder) if f.endswith("_pearsonR.npy")])

for fname in file_list:
    matrix = np.load(os.path.join(folder, fname))
    df = pd.DataFrame(matrix)

    csv_name = fname.replace(".npy", ".csv")
    df.to_csv(os.path.join(folder_1, csv_name), index=False)


In [21]:
!{sys.executable} -m pip install pyreadr

   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   --------------- ------------------------ 0.5/1.4 MB 1.7 MB/s eta 0:00:01
   ------------------------------ --------- 1.0/1.4 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 2.0 MB/s eta 0:00:00
